spring:
  application:
    name: yao-user-center-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yao-usercenter
    username: root
    password: 6825
  session:
    timeout: 86400
server:
  port: 8088
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
